### ISSUE TITLE
Solve github security alerts

### ISSUE THREAD

**Issue by robert-zaremba** [near-clp/nearswap-ui#16]
We have 2 alerts: https://github.com/near-clp/nearswap-ui/network/alerts

**Comment by amityadav0** [comment]
I cannot access this link
![404](https://user-images.githubusercontent.com/26249903/99904396-96e07e00-2cf0-11eb-9ed8-ffc7863aaee8.png)

**Comment by robert-zaremba** [comment]
### First issue: 
![image](https://user-images.githubusercontent.com/811701/99916404-63125200-2d0a-11eb-84e8-1f7bcffd2454.png)

### Second one:

![image](https://user-images.githubusercontent.com/811701/99916421-71f90480-2d0a-11eb-9186-7a281a4683fb.png)
