### ISSUE TITLE
Implement navigational URLs

### ISSUE THREAD

**Issue by jamesondh** [near-clp/nearswap-ui#18]
Currently, when a transaction is made and the user is redirected to the NEAR wallet, the view state is reset. (Example: a user goes to add liquidity to the pool and when redirected back to NEARswap, they will be taken back to the swap view rather than the correct pool view.) Navigational URLs are needed so that the correct view is loaded when the user is redirected back.

[React Router ](https://reactrouter.com/) seems to be the best choice to implement this.

**Comment by robert-zaremba** [comment]
There is also https://github.com/molefrog/wouter/, I highly recommend it. Much better and less boilerplate than the react router.
